

# navigation
nav:
  - index:
    - index: index.md
  - "Coding Standard":
    - index: coding-standard/index.md
  - "Docs for dimensium-base":
    - index: dimensium-base/index.md
  







theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
  logo: assets/images/dimensium-logo.svg


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer

    - toc.integrate

    - content.action.edit
    - content.action.view



  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-ruler
    view: material/eye



plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      # enabled: !ENV [CI, false]

      # fallback_to_build_date: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dimensium



  generator: true # TRUEEEEEEEEEEEEEEEEE ALWAYS


# site fundamental configurations

site_name: "Dimensium Docs"
site_description: "The official documentation repository of Dimensium, using mkdocs with material theme for mkdocs."
site_author: "The Dimensium Software Organization"
site_url: "https://dimensium.github.io"
strict: false

# repository configurations
repo_name: "dimensium/docs"
repo_url: "https://github.com/dimensium/docs"
edit_uri: "https://github.com/dimensium/docs/edit/master/docs"

# copyright
copyright: "Copyright &copy; 2023 Dimensium Software Organization"

# favicon: assets/images/dimensium-logo.svg